### PR TITLE
Got it to compile with stack LTS-15.5

### PR DESCRIPTION
**Pull request by wbadart**
Hey @kindaro, I've been trying to get yamadapc's hpack-convert to compile with a more modern stack snapshot. After struggling a bit, I saw that you opened https://github.com/yamadapc/hpack-convert/pull/16, which gets most of the way there for LTS-15.5. Here are some tweaks that get the package to compile all the way. (Still having some issues w/ the unit tests, see 3e43406 for details.)

Please let me know your thoughts!

### CODE REVIEW

**Comment by kindaro** [comment]
Hello Will. Thank you for stopping by. I shall look into it as soon as I can. Please remind me if I show no activity in a few days.

**Comment by kindaro** [comment]
@wbadart  Would you agree to bump the version number? Currently it goes backwards! Then I am going to merge it and see what happens. It was never intended to be a perfect package from my side — good enough that it runs. Surely I would also welcome any future work on this, all kinds of fixing and polishing, but I would rate that as low priority.

**Comment by wbadart** [comment]
Ha, didn't even notice that. Would definitely agree.

**Comment by wbadart** [comment]
Awesome. Let me know if you're able to make any progress on the unit tests (like I mentioned in the commit message, I think the failures are mostly related to quoting and error messaging). I'll be working on them from my end as time permits.

**Pull request merged**
